normalize X to zero mean

calculate covariance matrix Σ

find [orthonormal] eigenvectors of Σ

Av=ev  ==> e eigenvalue/ v eigenvector

In [1]:
import numpy as np

In [29]:
X=np.array([[1,2,3,4,5,6,7,777,7],[2,3,4,3,2,2,444,56,9]])

In [30]:
X

array([[  1,   2,   3,   4,   5,   6,   7, 777,   7],
       [  2,   3,   4,   3,   2,   2, 444,  56,   9]])

In [31]:
mu = X.mean(axis=0)

In [32]:
mu

array([  1.5,   2.5,   3.5,   3.5,   3.5,   4. , 225.5, 416.5,   8. ])

In [33]:
X = X - mu

In [38]:
X.shape

(2, 9)

In [35]:
sigma = X.T @ X##np.dot(X.T, X)

In [37]:
sigma.shape

(9, 9)

In [39]:
eigvals, eigvecs = np.linalg.eig(sigma)

In [40]:
eigvals

array([ 0.00000000e+00+0.00000000e+00j,  3.55421500e+05+0.00000000e+00j,
       -4.45868211e-15+0.00000000e+00j,  6.81780334e-24+0.00000000e+00j,
        1.15311657e-29+5.92795516e-30j,  1.15311657e-29-5.92795516e-30j,
       -8.87753291e-30+0.00000000e+00j,  3.96610756e-31+0.00000000e+00j,
        1.85585912e-46+0.00000000e+00j])

In [41]:
eigvals.shape

(9,)

In [42]:
eigvecs

array([[-9.99999297e-01+0.00000000e+00j, -1.18607774e-03+0.00000000e+00j,
        -3.71058342e-04+0.00000000e+00j, -3.70542309e-04+0.00000000e+00j,
         3.45313631e-01-1.84379736e-01j,  3.45313631e-01+1.84379736e-01j,
         3.68655697e-01+0.00000000e+00j,  5.44549734e-01+0.00000000e+00j,
        -9.99999297e-01+0.00000000e+00j],
       [ 1.40678139e-06+0.00000000e+00j, -1.18607774e-03+0.00000000e+00j,
        -3.71058343e-04+0.00000000e+00j,  5.21839770e-10+0.00000000e+00j,
        -4.85781132e-07+2.59382164e-07j, -4.85781132e-07-2.59382164e-07j,
        -5.18618339e-07+0.00000000e+00j, -7.66062970e-07+0.00000000e+00j,
         1.40678139e-06+0.00000000e+00j],
       [ 1.40678139e-06+0.00000000e+00j, -1.18607774e-03+0.00000000e+00j,
        -3.71058342e-04+0.00000000e+00j, -3.71030160e-04+0.00000000e+00j,
         7.06404896e-01+0.00000000e+00j,  7.06404896e-01-0.00000000e+00j,
        -3.69404801e-01+0.00000000e+00j,  2.65584476e-02+0.00000000e+00j,
         1.40678139e-06+0.00

In [44]:
eigvecs.shape

(9, 9)

In [45]:
order = np.argsort(eigvals)[::-1]

In [46]:
order

array([1, 3, 4, 5, 7, 8, 0, 6, 2], dtype=int64)

In [47]:
components = eigvecs[:, order[:2]]

In [48]:
components

array([[-1.18607774e-03+0.j, -3.70542309e-04+0.j],
       [-1.18607774e-03+0.j,  5.21839770e-10+0.j],
       [-1.18607774e-03+0.j, -3.71030160e-04+0.j],
       [ 1.18607774e-03+0.j,  3.71030160e-04+0.j],
       [ 3.55823321e-03+0.j, -2.25378639e-02+0.j],
       [ 4.74431095e-03+0.j,  1.48412064e-03+0.j],
       [-5.18315971e-01+0.j,  8.54926997e-01+0.j],
       [ 8.55162049e-01+0.j,  5.18255448e-01+0.j],
       [-2.37215548e-03+0.j, -7.42060320e-04+0.j]])

In [49]:
# projection
Z = X @ components

In [50]:
Z

array([[ 4.21557529e+02+0.j, -1.18251763e-14+0.j],
       [-4.21557529e+02+0.j,  1.18251763e-14+0.j]])